# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mox/.owncloud/research/SXS/toy_scalar_spectral

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mox/.owncloud/research/SXS/toy_scalar_spectral

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mox/.owncloud/research/SXS/toy_scalar_spectral/CMakeFiles /home/mox/.owncloud/research/SXS/toy_scalar_spectral/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mox/.owncloud/research/SXS/toy_scalar_spectral/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ScalarToyLib

# Build rule for target.
ScalarToyLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ScalarToyLib
.PHONY : ScalarToyLib

# fast build rule for target.
ScalarToyLib/fast:
	$(MAKE) -f CMakeFiles/ScalarToyLib.dir/build.make CMakeFiles/ScalarToyLib.dir/build
.PHONY : ScalarToyLib/fast

#=============================================================================
# Target rules for targets named run_wave

# Build rule for target.
run_wave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_wave
.PHONY : run_wave

# fast build rule for target.
run_wave/fast:
	$(MAKE) -f CMakeFiles/run_wave.dir/build.make CMakeFiles/run_wave.dir/build
.PHONY : run_wave/fast

run_wave.o: run_wave.cpp.o

.PHONY : run_wave.o

# target to build an object file
run_wave.cpp.o:
	$(MAKE) -f CMakeFiles/run_wave.dir/build.make CMakeFiles/run_wave.dir/run_wave.cpp.o
.PHONY : run_wave.cpp.o

run_wave.i: run_wave.cpp.i

.PHONY : run_wave.i

# target to preprocess a source file
run_wave.cpp.i:
	$(MAKE) -f CMakeFiles/run_wave.dir/build.make CMakeFiles/run_wave.dir/run_wave.cpp.i
.PHONY : run_wave.cpp.i

run_wave.s: run_wave.cpp.s

.PHONY : run_wave.s

# target to generate assembly for a file
run_wave.cpp.s:
	$(MAKE) -f CMakeFiles/run_wave.dir/build.make CMakeFiles/run_wave.dir/run_wave.cpp.s
.PHONY : run_wave.cpp.s

scalarFunction.o: scalarFunction.cpp.o

.PHONY : scalarFunction.o

# target to build an object file
scalarFunction.cpp.o:
	$(MAKE) -f CMakeFiles/ScalarToyLib.dir/build.make CMakeFiles/ScalarToyLib.dir/scalarFunction.cpp.o
.PHONY : scalarFunction.cpp.o

scalarFunction.i: scalarFunction.cpp.i

.PHONY : scalarFunction.i

# target to preprocess a source file
scalarFunction.cpp.i:
	$(MAKE) -f CMakeFiles/ScalarToyLib.dir/build.make CMakeFiles/ScalarToyLib.dir/scalarFunction.cpp.i
.PHONY : scalarFunction.cpp.i

scalarFunction.s: scalarFunction.cpp.s

.PHONY : scalarFunction.s

# target to generate assembly for a file
scalarFunction.cpp.s:
	$(MAKE) -f CMakeFiles/ScalarToyLib.dir/build.make CMakeFiles/ScalarToyLib.dir/scalarFunction.cpp.s
.PHONY : scalarFunction.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ScalarToyLib"
	@echo "... run_wave"
	@echo "... run_wave.o"
	@echo "... run_wave.i"
	@echo "... run_wave.s"
	@echo "... scalarFunction.o"
	@echo "... scalarFunction.i"
	@echo "... scalarFunction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

